<div class="footer-popular-tag">
    <?php
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('popular-tag-footer')
        ->toHtml();
    ?>
    <ul>
        <li>
            <button><a href="#">New In</a</button>
        </li>
        <li>
            <button><a href="#">Men's</a></button>
        </li>
        <li>
            <button><a href="#">Classes</a></button>
        </li>
        <li>
            <button><a href="#">Best Sellers</a></button>
        </li>
        <li>
            <button><a href="#">Top Brands</a></button>
        </li>
        <li>
            <button><a href="#">Sale & Special Offers</a></button>
        </li>
        <li>
            <button><a href="#">Lookbook</a></button>
        </li>
        <li>
            <button><a href="#">Top view</a></button>
        </li>
        <li>
            <button><a href="#">View all</a></button>
        </li>
    </ul>
</div>